/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/demo/scenarios/{scenario_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset demo scenario (load seed/, all-or-nothing) */
        post: operations["resetScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/forecasts/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh forecast for a service run */
        post: operations["refreshForecast"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ops overview dashboard (read-only) */
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/seatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seat x segment heatmap (read-only) */
        get: operations["getSeatmap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast + segment load + bid-price analytics (read-only) */
        get: operations["getAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decisions/{decision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decision detail / audit trail */
        get: operations["getDecision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an offer (same-seat gap search + pricing, no seat held) */
        post: operations["createOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/holds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomic hold on the offer's seat plan */
        post: operations["createHold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{hold_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm hold (HELD -> SOLD), never re-prices, idempotent */
        post: operations["confirmBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a backtest run (>=5 seeds) */
        post: operations["createBacktest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backtest report (median + range, baseline vs Âu Lạc) */
        get: operations["getBacktest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        SeatState: "FREE" | "HELD" | "SOLD";
        /** @enum {string} */
        OfferDecision: "ACCEPT" | "REJECT";
        /** @enum {string} */
        HoldStatus: "ACTIVE" | "CONFIRMED" | "EXPIRED" | "CANCELLED";
        /** @enum {string} */
        ErrorCode: "NO_SAME_SEAT_OPTION" | "SOLD_OUT_TRUE" | "ALLOCATION_REJECTED" | "STALE_SNAPSHOT" | "SEAT_CONFLICT" | "OFFER_EXPIRED" | "HOLD_EXPIRED" | "POLICY_UNAVAILABLE";
        ErrorEnvelope: {
            error_code: components["schemas"]["ErrorCode"];
            message: string;
            details?: Record<string, never>;
        };
        ResetResponse: {
            data?: {
                service_run_id?: string;
                matrix_version?: number;
                forecast_version?: number;
                policy_version?: number;
                checksum?: string;
            };
            message?: string;
        };
        OverviewResponse: {
            data?: {
                overall_occupancy?: number;
                total_revenue_vnd?: number;
                empty_seat_km?: number;
                passenger_km?: number;
                false_sold_out_rate?: number;
                bottlenecks?: {
                    segment_id?: number;
                    name?: string;
                    occupancy?: number;
                }[];
                underused?: {
                    segment_id?: number;
                    name?: string;
                    occupancy?: number;
                }[];
                recent_decisions?: {
                    decision_id?: string;
                    action?: string;
                    /** Format: date-time */
                    time?: string;
                }[];
            };
        };
        SeatmapResponse: {
            data?: {
                matrix_version?: number;
                segments?: {
                    segment_id?: number;
                    name?: string;
                }[];
                seats?: {
                    seat_id?: string;
                    seat_class?: string;
                    states?: {
                        [key: string]: components["schemas"]["SeatState"];
                    };
                    reused_gap_segments?: number[];
                }[];
            };
        };
        AnalyticsResponse: {
            data?: {
                forecasts?: {
                    origin?: string;
                    dest?: string;
                    demand_predicted?: number;
                    confidence?: number;
                }[];
                segment_loads?: {
                    segment_id?: number;
                    occupancy?: number;
                    remaining_capacity?: number;
                }[];
                allocations?: {
                    segment_id?: number;
                    bid_price_vnd?: number;
                    protection_level?: string;
                }[];
            };
        };
        DecisionDetailResponse: {
            data?: {
                decision_id?: string;
                action?: string;
                base_fare?: number;
                ai_suggested_price?: number;
                final_price?: number;
                bid_price_total?: number;
                bid_price_breakdown?: {
                    [key: string]: number;
                };
                violations?: string[];
                audit_timeline?: {
                    step?: string;
                    /** Format: date-time */
                    time?: string;
                    note?: string;
                }[];
            };
        };
        OfferRequest: {
            service_run_id: string;
            origin_station_id: string;
            dest_station_id: string;
            seat_class: string;
            quantity: number;
        };
        OfferResponse: {
            data?: {
                offer_id?: string;
                service_run_id?: string;
                matrix_version?: number;
                forecast_version?: number;
                policy_version?: number;
                decision?: components["schemas"]["OfferDecision"];
                seat_plan?: {
                    seat_id?: string;
                    segment_from?: number;
                    segment_to?: number;
                    reused_gap?: boolean;
                    requires_seat_change?: boolean;
                }[];
                pricing?: {
                    gia_goc_vnd?: number;
                    gia_niem_yet_vnd?: number;
                    gia_cuoi_vnd?: number;
                    rules_fired?: {
                        rule_id?: string;
                        he_so?: number;
                        thu_tu?: number;
                    }[];
                    clamped?: boolean;
                    che_do_gia?: string;
                };
                bid?: {
                    total_vnd?: number;
                    by_segment?: {
                        [key: string]: number;
                    };
                };
                decision_record_id?: string;
                /** Format: date-time */
                expires_at?: string;
            };
        };
        HoldRequest: {
            offer_id: string;
            expected_matrix_version: number;
            passenger_name?: string;
        };
        HoldResponse: {
            data?: {
                hold_id?: string;
                status?: components["schemas"]["HoldStatus"];
                /** Format: date-time */
                expires_at?: string;
                new_matrix_version?: number;
            };
        };
        ConfirmResponse: {
            data?: {
                booking_id?: string;
                status?: string;
                final_price_vnd?: number;
                decision_record_id?: string;
            };
        };
        BacktestReportResponse: {
            data?: {
                status?: string;
                baseline_metrics?: {
                    revenue_median?: number;
                    acceptance_rate?: number;
                };
                ai_metrics?: {
                    revenue_median?: number;
                    acceptance_rate?: number;
                };
            };
        };
    };
    responses: {
        /** @description 400 Bad Request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 404 Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 409 STALE_SNAPSHOT | SEAT_CONFLICT */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 410 OFFER_EXPIRED | HOLD_EXPIRED */
        Gone: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 503 POLICY_UNAVAILABLE — never silently fall back to a default price */
        PolicyUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    resetScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example golden_scenario_1 */
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "reset_clock": true,
                 *       "apply_golden_gap": true
                 *     }
                 */
                "application/json": {
                    reset_clock?: boolean;
                    apply_golden_gap?: boolean;
                };
            };
        };
        responses: {
            /** @description Scenario reset successfully (deterministic — same seed same checksum) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "service_run_id": "SE1_2026-06-15_LE",
                     *         "matrix_version": 1,
                     *         "forecast_version": 1,
                     *         "policy_version": 1,
                     *         "checksum": "abc123xyz"
                     *       },
                     *       "message": "Scenario reset successfully"
                     *     }
                     */
                    "application/json": components["schemas"]["ResetResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    refreshForecast: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "service_run_id": "SE1_2026-06-15_LE"
                 *     }
                 */
                "application/json": {
                    service_run_id: string;
                };
            };
        };
        responses: {
            /** @description Forecast updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Forecast updated",
                     *       "data": {
                     *         "forecast_version": 2
                     *       }
                     *     }
                     */
                    "application/json": {
                        message?: string;
                        data?: {
                            forecast_version?: number;
                        };
                    };
                };
            };
        };
    };
    getOverview: {
        parameters: {
            query: {
                service_run_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
        };
    };
    getSeatmap: {
        parameters: {
            query: {
                service_run_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeatmapResponse"];
                };
            };
        };
    };
    getAnalytics: {
        parameters: {
            query: {
                service_run_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
        };
    };
    getDecision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionDetailResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createOffer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "service_run_id": "SE1_2026-06-15_LE",
                 *       "origin_station_id": "THO",
                 *       "dest_station_id": "DHO",
                 *       "seat_class": "NGOI_MEM_DH",
                 *       "quantity": 1
                 *     }
                 */
                "application/json": components["schemas"]["OfferRequest"];
            };
        };
        responses: {
            /** @description Offer created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferResponse"];
                };
            };
            /** @description NO_SAME_SEAT_OPTION | SOLD_OUT_TRUE | ALLOCATION_REJECTED */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error_code": "ALLOCATION_REJECTED",
                     *       "message": "Giá vé không bù đủ chi phí cơ hội các đoạn chiếm dụng",
                     *       "details": {
                     *         "final_price_vnd": 380000,
                     *         "bid_price_total_vnd": 420000,
                     *         "decision_record_id": "dr_8900"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            503: components["responses"]["PolicyUnavailable"];
        };
    };
    createHold: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "offer_id": "offer_9981",
                 *       "expected_matrix_version": 5,
                 *       "passenger_name": "Nguyễn Văn A"
                 *     }
                 */
                "application/json": components["schemas"]["HoldRequest"];
            };
        };
        responses: {
            /** @description Hold active */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            410: components["responses"]["Gone"];
        };
    };
    confirmBooking: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                hold_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Confirmed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmResponse"];
                };
            };
            410: components["responses"]["Gone"];
        };
    };
    createBacktest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "event_stream_id": "stream_demo_1",
                 *       "seeds": [
                 *         "20260717",
                 *         "20260718",
                 *         "20260719",
                 *         "20260720",
                 *         "20260721"
                 *       ]
                 *     }
                 */
                "application/json": {
                    event_stream_id: string;
                    seeds: string[];
                };
            };
        };
        responses: {
            /** @description Backtest started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Backtest started",
                     *       "data": {
                     *         "report_id": "bt_12345"
                     *       }
                     *     }
                     */
                    "application/json": {
                        message?: string;
                        data?: {
                            report_id?: string;
                        };
                    };
                };
            };
        };
    };
    getBacktest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestReportResponse"];
                };
            };
        };
    };
}
