/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/demo/scenarios/{scenario_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset demo scenario (load seed/, all-or-nothing) */
        post: operations["resetScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/forecasts/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh forecast for a service run */
        post: operations["refreshForecast"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ops overview dashboard (read-only) */
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/seatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seat x segment heatmap (read-only) */
        get: operations["getSeatmap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast + segment load + bid-price analytics (read-only) */
        get: operations["getAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List real service runs in the DB (run-picker, replaces hardcoded golden run) */
        get: operations["listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full station catalog (id -> name), for display labels */
        get: operations["listStations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/runs/{service_run_id}/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ordered stops for one run (real topology, may differ from the golden 8-station network) */
        get: operations["getRunStops"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decisions/{decision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decision detail / audit trail */
        get: operations["getDecision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an offer (same-seat gap search + pricing, no seat held) */
        post: operations["createOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/holds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomic hold on the offer's seat plan */
        post: operations["createHold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{hold_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm hold (HELD -> SOLD), never re-prices, idempotent */
        post: operations["confirmBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a backtest run (>=5 seeds) */
        post: operations["createBacktest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backtest report (median + range, baseline vs Âu Lạc) */
        get: operations["getBacktest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allocation/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-solve DLP and propose a new quota/booking-limit version (PENDING)
         * @description Re-solves the DLP (reuses the P2 bid-price cache, does not solve the LP twice), diffs booking_limit per (segment, journey-length band, seat class) against the current ACTIVE version, and stores the result as a new PENDING quota_version. Proposal-only — does not enforce booking_limit in /offers.
         */
        post: operations["refreshAllocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allocation/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one quota version (PENDING / ACTIVE / REJECTED / ROLLED_BACK) */
        get: operations["getAllocationVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allocation/{version}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a PENDING quota version (becomes ACTIVE)
         * @description Requires X-Actor-Role revenue_manager|admin. Demotes the previously ACTIVE version to ROLLED_BACK.
         */
        post: operations["approveAllocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allocation/{version}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a PENDING quota version
         * @description Requires X-Actor-Role revenue_manager|admin.
         */
        post: operations["rejectAllocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allocation/{version}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-activate an old quota version (emergency revert)
         * @description Requires X-Actor-Role revenue_manager|admin. Unlike approve, the source version may be in any status (PENDING/REJECTED/ROLLED_BACK) — rollback is meant for an operator returning to any known-good version quickly.
         */
        post: operations["rollbackAllocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List PENDING waitlist entries (priority score descending) */
        get: operations["listWaitlist"];
        put?: never;
        /**
         * Join the waitlist (customer opts in after NO_SAME_SEAT_OPTION)
         * @description Not auto-added on offer failure — the customer must actively choose to wait.
         */
        post: operations["addWaitlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/waitlist/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Try to match PENDING waitlist entries against currently free seats
         * @description ponytail: no background worker in this demo — an operator (or a future scheduler) triggers this explicitly after cancellations/hold-expiries. A match reuses the real /offers -> /holds pipeline (no separate pricing/CAS logic) so a matched entry gets a real Hold the customer can pay within the normal hold TTL.
         */
        post: operations["matchWaitlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/group/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose a same-car/compartment seat plan for a group (proposal only, no hold) */
        post: operations["quoteGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers/{offer_id}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manually override an offer's price, within the approved guardrail
         * @description Requires X-Actor-Role revenue_manager|admin. Only allowed before a Hold exists for the offer (a held price is honored/immutable). New price must stay within [floor_ratio, ceiling_ratio] * base_fare — never outside the approved band.
         */
        post: operations["overrideOfferPrice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        SeatState: "FREE" | "HELD" | "SOLD";
        /** @enum {string} */
        OfferDecision: "ACCEPT" | "REJECT";
        /** @enum {string} */
        HoldStatus: "ACTIVE" | "CONFIRMED" | "EXPIRED" | "CANCELLED";
        /** @enum {string} */
        ErrorCode: "NO_SAME_SEAT_OPTION" | "SOLD_OUT_TRUE" | "ALLOCATION_REJECTED" | "STALE_SNAPSHOT" | "SEAT_CONFLICT" | "OFFER_EXPIRED" | "HOLD_EXPIRED" | "POLICY_UNAVAILABLE" | "CONSENT_REQUIRED" | "RESOURCE_NOT_FOUND" | "FORBIDDEN" | "GUARDRAIL_VIOLATION";
        ErrorEnvelope: {
            error_code: components["schemas"]["ErrorCode"];
            message: string;
            details?: Record<string, never>;
        };
        ResetResponse: {
            data?: {
                service_run_id?: string;
                matrix_version?: number;
                forecast_version?: number;
                policy_version?: number;
                checksum?: string;
            };
            message?: string;
        };
        OverviewResponse: {
            data?: {
                overall_occupancy?: number;
                total_revenue_vnd?: number;
                empty_seat_km?: number;
                passenger_km?: number;
                false_sold_out_rate?: number;
                bottlenecks?: {
                    segment_id?: number;
                    name?: string;
                    occupancy?: number;
                }[];
                underused?: {
                    segment_id?: number;
                    name?: string;
                    occupancy?: number;
                }[];
                recent_decisions?: {
                    decision_id?: string;
                    action?: string;
                    /** Format: date-time */
                    time?: string;
                }[];
            };
        };
        SeatmapResponse: {
            data?: {
                matrix_version?: number;
                segments?: {
                    segment_id?: number;
                    name?: string;
                }[];
                seats?: {
                    seat_id?: string;
                    seat_class?: string;
                    states?: {
                        [key: string]: components["schemas"]["SeatState"];
                    };
                    reused_gap_segments?: number[];
                }[];
            };
        };
        AnalyticsResponse: {
            data?: {
                forecasts?: {
                    origin?: string;
                    dest?: string;
                    demand_predicted?: number;
                    confidence?: number;
                }[];
                segment_loads?: {
                    segment_id?: number;
                    occupancy?: number;
                    remaining_capacity?: number;
                }[];
                allocations?: {
                    segment_id?: number;
                    bid_price_vnd?: number;
                    protection_level?: string;
                }[];
            };
        };
        RunsResponse: {
            data?: {
                runs?: {
                    service_run_id?: string;
                    train_id?: string;
                    /** Format: date */
                    service_date?: string;
                    direction?: string;
                    status?: string;
                }[];
            };
        };
        StationsResponse: {
            data?: {
                stations?: {
                    station_id?: string;
                    station_name?: string;
                    ly_trinh_km?: number;
                }[];
            };
        };
        StopsResponse: {
            data?: {
                stops?: {
                    stop_sequence?: number;
                    station_id?: string;
                    station_name?: string;
                }[];
            };
        };
        DecisionDetailResponse: {
            data?: {
                decision_id?: string;
                action?: string;
                base_fare?: number;
                ai_suggested_price?: number;
                final_price?: number;
                bid_price_total?: number;
                bid_price_breakdown?: {
                    [key: string]: number;
                };
                violations?: string[];
                audit_timeline?: {
                    step?: string;
                    /** Format: date-time */
                    time?: string;
                    note?: string;
                }[];
            };
        };
        OfferRequest: {
            service_run_id: string;
            origin_station_id: string;
            dest_station_id: string;
            seat_class: string;
            quantity: number;
            /**
             * @description Cao tuổi/khuyết tật/trẻ đi một mình — không bao giờ nhận phương án ghép nhiều ghế (P5).
             * @default false
             */
            priority_passenger: boolean;
        };
        OfferResponse: {
            data?: {
                offer_id?: string;
                service_run_id?: string;
                matrix_version?: number;
                forecast_version?: number;
                policy_version?: number;
                decision?: components["schemas"]["OfferDecision"];
                seat_plan?: {
                    seat_id?: string;
                    segment_from?: number;
                    segment_to?: number;
                    reused_gap?: boolean;
                    requires_seat_change?: boolean;
                }[];
                /** @description true khi seat_plan có >=2 leg (ghép nhiều ghế, P5) — /holds từ chối nếu HoldRequest.consent != true. */
                requires_customer_consent?: boolean;
                /** @description Ga đổi chỗ giữa các leg (rỗng nếu same-seat). */
                change_station_ids?: string[];
                /** @description = len(seat_plan) - 1 */
                so_lan_doi_cho?: number;
                pricing?: {
                    gia_goc_vnd?: number;
                    gia_niem_yet_vnd?: number;
                    gia_cuoi_vnd?: number;
                    rules_fired?: {
                        rule_id?: string;
                        he_so?: number;
                        thu_tu?: number;
                    }[];
                    clamped?: boolean;
                    che_do_gia?: string;
                };
                bid?: {
                    total_vnd?: number;
                    by_segment?: {
                        [key: string]: number;
                    };
                };
                decision_record_id?: string;
                /** Format: date-time */
                expires_at?: string;
            };
        };
        HoldRequest: {
            offer_id: string;
            expected_matrix_version: number;
            passenger_name?: string;
            /**
             * @description Bắt buộc true khi offer.requires_customer_consent — thiếu -> 422 CONSENT_REQUIRED (P5).
             * @default false
             */
            consent: boolean;
        };
        HoldResponse: {
            data?: {
                hold_id?: string;
                status?: components["schemas"]["HoldStatus"];
                /** Format: date-time */
                expires_at?: string;
                new_matrix_version?: number;
            };
        };
        ConfirmResponse: {
            data?: {
                booking_id?: string;
                status?: string;
                final_price_vnd?: number;
                decision_record_id?: string;
            };
        };
        BacktestReportResponse: {
            data?: {
                status?: string;
                baseline_metrics?: {
                    revenue_median?: number;
                    acceptance_rate?: number;
                };
                ai_metrics?: {
                    revenue_median?: number;
                    acceptance_rate?: number;
                };
            };
        };
        QuotaRow: {
            /** @description 1-based segment_id (L1..L7) */
            khu_gian_id?: number;
            /** @enum {string} */
            loai_hanh_trinh?: "ngan" | "trung" | "dai";
            seat_class?: string;
            /** @description Demand accepted by the DLP for this key */
            quota?: number;
            /** @description Nested booking limit — ngan = remaining − protected trung/dai */
            booking_limit?: number;
            bid_price?: number;
        };
        AllocationDecisionRequest: {
            /**
             * @description Display name recorded in the audit log — role itself is checked via X-Actor-Role.
             * @default revenue_manager
             */
            decided_by: string;
        };
        QuotaVersionResponse: {
            data?: {
                version?: number;
                /** @enum {string} */
                status?: "PENDING" | "ACTIVE" | "REJECTED" | "ROLLED_BACK";
                quota?: components["schemas"]["QuotaRow"][];
                /** @description Diff vs the previous ACTIVE version — empty on the very first version. */
                proposal?: {
                    khu_gian_id?: number;
                    loai_hanh_trinh?: string;
                    seat_class?: string;
                    /** @enum {string} */
                    action?: "MO_THEM" | "SIET_LAI";
                    limit_cu?: number;
                    limit_moi?: number;
                }[];
                decided_by?: string | null;
                /** Format: date-time */
                created_at?: string;
                /** Format: date-time */
                decided_at?: string | null;
            };
        };
        WaitlistAddRequest: {
            service_run_id: string;
            origin_station_id: string;
            dest_station_id: string;
            seat_class: string;
            /** @default 1 */
            quantity: number;
            /**
             * @description Lead time (days before departure)
             * @default 14
             */
            u: number;
            /** @default false */
            priority_passenger: boolean;
            /** @default KHONG */
            csxh_doi_tuong: string;
        };
        WaitlistAddResponse: {
            data?: {
                /** Format: uuid */
                waitlist_id?: string;
                /** @description Deterministic score (fare value 0.4 + urgency 0.3 + segment scarcity 0.2 + CSXH flag 0.1) — same formula as app.waitlist.WaitlistManager, no personal data used to differentiate. */
                priority_score?: number;
                /** @enum {string} */
                status?: "PENDING";
            };
        };
        WaitlistEntry: {
            /** Format: uuid */
            waitlist_id?: string;
            origin_station_id?: string;
            dest_station_id?: string;
            seat_class?: string;
            priority_score?: number;
            priority_passenger?: boolean;
            quantity?: number;
            /** Format: date-time */
            created_at?: string;
        };
        WaitlistListResponse: {
            data?: {
                pending?: components["schemas"]["WaitlistEntry"][];
            };
        };
        WaitlistMatchResponse: {
            data?: {
                matched?: {
                    /** Format: uuid */
                    waitlist_id?: string;
                    hold_id?: string;
                    /** Format: date-time */
                    expires_at?: string;
                }[];
                still_pending?: number;
            };
        };
        GroupQuoteRequest: {
            service_run_id: string;
            origin_station_id: string;
            dest_station_id: string;
            seat_class: string;
            n_khach: number;
        };
        GroupQuoteResponse: {
            data?: {
                kha_thi?: boolean;
                seat_class?: string;
                assignments?: {
                    seat_idx?: number;
                    seg_from?: number;
                    seg_to?: number;
                    ga_di?: string;
                    ga_den?: string;
                    seat_id?: string;
                }[];
                /** @description Car indices used (fewest cars is the top-priority objective). */
                toa?: number[];
                /** @description 0..1 — fraction of seats that are adjacent */
                diem_lien_ke?: number;
                /** @description Number of distinct compartments used, minus 1 */
                so_lan_tach?: number;
                ghi_chu?: string;
            };
        };
        OverrideRequest: {
            new_price_vnd: number;
            reason: string;
            /** @default revenue_manager */
            decided_by: string;
        };
        OverrideResponse: {
            data?: {
                offer_id?: string;
                old_price_vnd?: number;
                new_price_vnd?: number;
                /** Format: date-time */
                expires_at?: string;
            };
        };
    };
    responses: {
        /** @description 400 Bad Request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 404 Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 409 STALE_SNAPSHOT | SEAT_CONFLICT */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 410 OFFER_EXPIRED | HOLD_EXPIRED */
        Gone: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 503 POLICY_UNAVAILABLE — never silently fall back to a default price */
        PolicyUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 403 FORBIDDEN — role không đủ quyền (X-Actor-Role không phải revenue_manager/admin) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
        /**
         * @description P7.2/P7.6 — role check thô qua header (KHÔNG phải RBAC/JWT thật, chỉ đủ để demo quy trình cần role duyệt). Chỉ revenue_manager|admin được phép.
         * @example revenue_manager
         */
        ActorRole: "user" | "revenue_manager" | "admin";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    resetScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example golden_scenario_1 */
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "reset_clock": true,
                 *       "apply_golden_gap": true
                 *     }
                 */
                "application/json": {
                    reset_clock?: boolean;
                    apply_golden_gap?: boolean;
                };
            };
        };
        responses: {
            /** @description Scenario reset successfully (deterministic — same seed same checksum) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "service_run_id": "SE1_2026-06-15_LE",
                     *         "matrix_version": 1,
                     *         "forecast_version": 1,
                     *         "policy_version": 1,
                     *         "checksum": "abc123xyz"
                     *       },
                     *       "message": "Scenario reset successfully"
                     *     }
                     */
                    "application/json": components["schemas"]["ResetResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    refreshForecast: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "service_run_id": "SE1_2026-06-15_LE"
                 *     }
                 */
                "application/json": {
                    service_run_id: string;
                };
            };
        };
        responses: {
            /** @description Forecast updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Forecast updated",
                     *       "data": {
                     *         "forecast_version": 2
                     *       }
                     *     }
                     */
                    "application/json": {
                        message?: string;
                        data?: {
                            forecast_version?: number;
                        };
                    };
                };
            };
        };
    };
    getOverview: {
        parameters: {
            query: {
                service_run_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
        };
    };
    getSeatmap: {
        parameters: {
            query: {
                service_run_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeatmapResponse"];
                };
            };
        };
    };
    getAnalytics: {
        parameters: {
            query: {
                service_run_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                limit?: number;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsResponse"];
                };
            };
        };
    };
    listStations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationsResponse"];
                };
            };
        };
    };
    getRunStops: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopsResponse"];
                };
            };
        };
    };
    getDecision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionDetailResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createOffer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "service_run_id": "SE1_2026-06-15_LE",
                 *       "origin_station_id": "THO",
                 *       "dest_station_id": "DHO",
                 *       "seat_class": "NGOI_MEM_DH",
                 *       "quantity": 1
                 *     }
                 */
                "application/json": components["schemas"]["OfferRequest"];
            };
        };
        responses: {
            /** @description Offer created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferResponse"];
                };
            };
            /** @description NO_SAME_SEAT_OPTION | SOLD_OUT_TRUE | ALLOCATION_REJECTED */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error_code": "ALLOCATION_REJECTED",
                     *       "message": "Giá vé không bù đủ chi phí cơ hội các đoạn chiếm dụng",
                     *       "details": {
                     *         "final_price_vnd": 380000,
                     *         "bid_price_total_vnd": 420000,
                     *         "decision_record_id": "dr_8900"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            503: components["responses"]["PolicyUnavailable"];
        };
    };
    createHold: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "offer_id": "offer_9981",
                 *       "expected_matrix_version": 5,
                 *       "passenger_name": "Nguyễn Văn A"
                 *     }
                 */
                "application/json": components["schemas"]["HoldRequest"];
            };
        };
        responses: {
            /** @description Hold active */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            410: components["responses"]["Gone"];
            /** @description CONSENT_REQUIRED — seat_plan có >=2 leg (ghép nhiều ghế) nhưng consent != true */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error_code": "CONSENT_REQUIRED",
                     *       "message": "Phương án ghép nhiều ghế cần khách xác nhận đồng ý đổi chỗ trước khi giữ ghế",
                     *       "details": {
                     *         "offer_id": "offer_9981",
                     *         "so_lan_doi_cho": 1
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    confirmBooking: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                hold_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Confirmed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmResponse"];
                };
            };
            410: components["responses"]["Gone"];
        };
    };
    createBacktest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "event_stream_id": "stream_demo_1",
                 *       "seeds": [
                 *         "20260717",
                 *         "20260718",
                 *         "20260719",
                 *         "20260720",
                 *         "20260721"
                 *       ]
                 *     }
                 */
                "application/json": {
                    event_stream_id: string;
                    seeds: string[];
                };
            };
        };
        responses: {
            /** @description Backtest started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Backtest started",
                     *       "data": {
                     *         "report_id": "bt_12345"
                     *       }
                     *     }
                     */
                    "application/json": {
                        message?: string;
                        data?: {
                            report_id?: string;
                        };
                    };
                };
            };
        };
    };
    getBacktest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestReportResponse"];
                };
            };
        };
    };
    refreshAllocation: {
        parameters: {
            query: {
                service_run_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New PENDING quota version created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaVersionResponse"];
                };
            };
            503: components["responses"]["PolicyUnavailable"];
        };
    };
    getAllocationVersion: {
        parameters: {
            query: {
                service_run_id: string;
            };
            header?: never;
            path: {
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaVersionResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    approveAllocation: {
        parameters: {
            query: {
                service_run_id: string;
            };
            header: {
                /**
                 * @description P7.2/P7.6 — role check thô qua header (KHÔNG phải RBAC/JWT thật, chỉ đủ để demo quy trình cần role duyệt). Chỉ revenue_manager|admin được phép.
                 * @example revenue_manager
                 */
                "X-Actor-Role": components["parameters"]["ActorRole"];
            };
            path: {
                version: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "decided_by": "nguyen_van_dieu_do"
                 *     }
                 */
                "application/json": components["schemas"]["AllocationDecisionRequest"];
            };
        };
        responses: {
            /** @description Version is now ACTIVE */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaVersionResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    rejectAllocation: {
        parameters: {
            query: {
                service_run_id: string;
            };
            header: {
                /**
                 * @description P7.2/P7.6 — role check thô qua header (KHÔNG phải RBAC/JWT thật, chỉ đủ để demo quy trình cần role duyệt). Chỉ revenue_manager|admin được phép.
                 * @example revenue_manager
                 */
                "X-Actor-Role": components["parameters"]["ActorRole"];
            };
            path: {
                version: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllocationDecisionRequest"];
            };
        };
        responses: {
            /** @description Version is now REJECTED */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaVersionResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    rollbackAllocation: {
        parameters: {
            query: {
                service_run_id: string;
            };
            header: {
                /**
                 * @description P7.2/P7.6 — role check thô qua header (KHÔNG phải RBAC/JWT thật, chỉ đủ để demo quy trình cần role duyệt). Chỉ revenue_manager|admin được phép.
                 * @example revenue_manager
                 */
                "X-Actor-Role": components["parameters"]["ActorRole"];
            };
            path: {
                version: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllocationDecisionRequest"];
            };
        };
        responses: {
            /** @description Version is now ACTIVE again */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaVersionResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listWaitlist: {
        parameters: {
            query: {
                service_run_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistListResponse"];
                };
            };
        };
    };
    addWaitlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "service_run_id": "SE1_2026-06-15_LE",
                 *       "origin_station_id": "HNO",
                 *       "dest_station_id": "NBI",
                 *       "seat_class": "NGOI_MEM_DH",
                 *       "u": 10
                 *     }
                 */
                "application/json": components["schemas"]["WaitlistAddRequest"];
            };
        };
        responses: {
            /** @description Entry queued as PENDING */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistAddResponse"];
                };
            };
        };
    };
    matchWaitlist: {
        parameters: {
            query: {
                service_run_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistMatchResponse"];
                };
            };
        };
    };
    quoteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "service_run_id": "SE1_2026-06-15_LE",
                 *       "origin_station_id": "HNO",
                 *       "dest_station_id": "NBI",
                 *       "seat_class": "NGOI_MEM_DH",
                 *       "n_khach": 8
                 *     }
                 */
                "application/json": components["schemas"]["GroupQuoteRequest"];
            };
        };
        responses: {
            /** @description Feasible plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupQuoteResponse"];
                };
            };
            /** @description NO_SAME_SEAT_OPTION — not enough seats free the whole journey for the group */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    overrideOfferPrice: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description P7.2/P7.6 — role check thô qua header (KHÔNG phải RBAC/JWT thật, chỉ đủ để demo quy trình cần role duyệt). Chỉ revenue_manager|admin được phép.
                 * @example revenue_manager
                 */
                "X-Actor-Role": components["parameters"]["ActorRole"];
            };
            path: {
                offer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "new_price_vnd": 109000,
                 *       "reason": "Khách VIP - đại lý yêu cầu giữ giá gốc",
                 *       "decided_by": "nguyen_van_dieu_do"
                 *     }
                 */
                "application/json": components["schemas"]["OverrideRequest"];
            };
        };
        responses: {
            /** @description Price overridden */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverrideResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description SEAT_CONFLICT — offer already has an ACTIVE/CONFIRMED hold (locked price is immutable) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description GUARDRAIL_VIOLATION — requested price outside [floor_ratio, ceiling_ratio] * F0 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error_code": "GUARDRAIL_VIOLATION",
                     *       "message": "Giá override 545.000đ ngoài dải guardrail [59.950;174.400]đ",
                     *       "details": {
                     *         "offer_id": "offer_34f261613c42",
                     *         "floor": 59950,
                     *         "ceiling": 174400,
                     *         "requested": 545000
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            503: components["responses"]["PolicyUnavailable"];
        };
    };
}
